# -*- coding: utf-8 -*-
"""NAASCOM case study 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJowoyWVRKfun9Ia8TlVTvs7DkdM8Toe
"""

import pandas as pd

data = {
    "Student": ["S1", "S2", "S3", "S4", "S5",
                "S6", "S7", "S8", "S9", "S10"],

    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],

    "Attendance": [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],

    "Assignment_Score": [55, 60, 65, 72, 78, 85, 88, 70, 80, 92],

    "Previous_Score": [58, 62, 68, 70, 76, 82, 86, 72, 79, 90],

    "Final_Score": [60, 64, 70, 75, 82, 88, 91, 74, 84, 94]
}

df = pd.DataFrame(data)

print(df)

print("Number of students:", len(df))

for column in df.columns:
    print(column)

print(df.dtypes)

print(df.head())

print("Last five records:")
print(df.tail())

df = pd.DataFrame(data)

print(df)

print(df)

print("Average values:")

print("Study Hours:", df["Study_Hours"].mean())
print("Attendance:", df["Attendance"].mean())
print("Assignment Score:", df["Assignment_Score"].mean())
print("Previous Score:", df["Previous_Score"].mean())
print("Final Score:", df["Final_Score"].mean())

highest = df["Final_Score"].idxmax()

print("Student with highest Final Score:")
print(df.loc[highest])

lowest = df["Final_Score"].idxmin()

print("Student with lowest Final Score:")
print(df.loc[lowest])

students = df[df["Attendance"] > 80]

print(students)

students = df[df["Final_Score"] > 80]

print(students)

print(df.describe())

import numpy as np
final_scores = np.array(df["Final_Score"])

print(final_scores)

mean = np.mean(final_scores)

print("Mean:", mean)

median = np.median(final_scores)

print("Median:", median)

maximum = np.max(final_scores)

print("Maximum:", maximum)

minimum = np.min(final_scores)

print("Minimum:", minimum)

std = np.std(final_scores)

print("Standard Deviation:", std)

import matplotlib.pyplot as plt
plt.scatter(df["Study_Hours"], df["Final_Score"])

plt.xlabel("Study Hours")
plt.ylabel("Final Score")
plt.title("Study Hours vs Final Score")

plt.show()

plt.scatter(df["Attendance"], df["Final_Score"])

plt.xlabel("Attendance")
plt.ylabel("Final Score")
plt.title("Attendance vs Final Score")

plt.show()

plt.hist(df["Final_Score"], bins=5)

plt.xlabel("Final Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Final Scores")

plt.show()

plt.bar(df["Student"], df["Final_Score"])

plt.xlabel("Student")
plt.ylabel("Final Score")
plt.title("Student-wise Final Scores")

plt.show()

X = df[["Study_Hours", "Attendance", "Assignment_Score"]].values

print("Matrix X:")
print(X)

import numpy as np

X = np.array([
    [2, 65, 55],
    [3, 70, 60],
    [4, 75, 65],
    [5, 80, 72],
    [6, 85, 78],
    [7, 90, 85],
    [8, 92, 88],
    [4, 78, 70],
    [6, 88, 80],
    [9, 95, 92]
])

print("Matrix X:")
print(X)

print("Shape of X:", X.shape)

XT = X.T

print("Transpose of X:")
print(XT)

XTX = np.dot(X.T, X)

print("X transpose X:")
print(XTX)

study_hours = np.array([2, 3, 4, 5, 6, 7, 8, 4, 6, 9])

final_scores = np.array([60, 64, 70, 75, 82, 88, 91, 74, 84, 94])

dot_product = np.dot(study_hours, final_scores)

print("Dot product:", dot_product)

def F(x):
    return 40 + 6*x - 0.2*x**2

def dF(x):
    return 6 - 0.4*x

for x in range(0, 11):
    print(x, F(x), dF(x))

import sympy as sp

x = sp.symbols('x')

L = 5*x - 0.2*x**2

integral = sp.integrate(L, x)

print("Integral:", integral)

import numpy as np

def L(x):
    return 5*x - 0.2*x**2

x = np.linspace(0, 10, 1000)
y = L(x)

area = np.trapezoid(y, x)

print("Numerical approximation:", area)

print("Study Hours vs Final Score:",
      df["Study_Hours"].corr(df["Final_Score"]))

print("Attendance vs Final Score:",
      df["Attendance"].corr(df["Final_Score"]))

print("Assignment Score vs Final Score:",
      df["Assignment_Score"].corr(df["Final_Score"]))

print("Previous Score vs Final Score:",
      df["Previous_Score"].corr(df["Final_Score"]))

import seaborn as sns
import matplotlib.pyplot as plt

correlation = df.corr(numeric_only=True)

sns.heatmap(correlation, annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap")
plt.show()

import numpy as np

# Input variables
X = df[["Study_Hours", "Attendance", "Assignment_Score"]].values

# Add a column of 1s for the intercept
X = np.column_stack((np.ones(len(X)), X))

# Output variable
Y = df["Final_Score"].values

# Calculate coefficients
beta = np.linalg.lstsq(X, Y, rcond=None)[0]

print("Coefficients:")
print(beta)

Y_pred = X @ beta

print("Predicted Final Scores:")
print(Y_pred)

average = df["Final_Score"].mean()

print("Average Final Score:", average)

print("Standard Deviation:",
      np.std(df["Final_Score"]))

highest = df.loc[df["Final_Score"].idxmax()]

print(highest)

